---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: studentcluster
  namespace: mongodb
spec:
  shardCount: 2
  mongodsPerShardCount: 3
  mongosCount: 2
  configServerCount: 3
  version: 4.0.6
  opsManager:
    configMapRef:
      name: opsmanager-config
  credentials: mongo-cloud-mgr
  type: ShardedCluster
  persistent: true
